### PR TITLE
Student_Applications

### PR DESCRIPTION
**Pull request by tifabi**
This page is being created as part of the Contributing 2.3.1 Exercise for Contrib.2. I've never done this before so hopefully it's ok..

### CODE REVIEW

**Comment by tifabi** [comment]
I was trying to add a section that was not covered but could be helpful. Let me re-evaluate and try something different to complete this exercise. I've also updated my name and avatar so you can see who I am.

**Comment by laszewsk** [comment]
I will provide you with some more instructions on how to do the commits. We have a special way to do this.

https://pypi.python.org/pypi/gitchangelog

All you need to do is to put 

new: usr:
chg: usr:
fix: usr:

in the commit msg as prefix

If its minor things that do not need to be communicated to everyone we use dev instead of usr. This could be spelling and grammar errors.

**Comment by laszewsk** [comment]
created new issue and closed: https://github.com/cloudmesh/classes/issues/596

**Comment by laszewsk** [comment]
Not sure. I do not have time to look into this but a TA shold take care of this.

**Comment by laszewsk** [comment]
i think there is a different issue been filed as there were too many things done in the pull request

a) the bio tool certainly does not belong in the contribution section, but could be placed elsewhere. I think i filed noew ticket on this.

b) I think but can not remember anymore that I integrated the spelling errors, blease check. 
I reopened and assigned to Saber

**Comment by ssheybani** [comment]
Hi @tifabi 
Thank you for your contribution. I have created a new directory and a file for this. You can go ahead and put your summary in technologies.rst , commit, and push it again to your own fork. Also please remove this file "Student Applications".

**Comment by laszewsk** [comment]
Saber it may be faster if you fix this yourself. This is not that difficult.

**Pull request merged**
