### PR TITLE
new:usr: improve: Overwriting other peoples reviews: Adding Review Comments for S17-IR-2001 and removing review comment for S17-IR-2006

### PR DESCRIPTION
**Pull request by karthik-anba**
Rebased and requesting new pull

### CODE REVIEW

**Comment by karthik-anba** [comment]
This may cause a conflict with #430 as the user is trying to review S17-IR-2006's work.

**Comment by karthik-anba** [comment]
I had wrongly reviewed S17-IR-2006's also. I am therefore removing the comments I had made

**Comment by laszewsk** [comment]
reject: you are overwriteing other peoples reviews

**Comment by laszewsk** [comment]
Your pull request can not be merged as you are overwriting other reviews for the entries. In order for you to not lose points I encourage you to fix your pull request while being in sync with the current repository. We like you to do this ASAP.

**Comment by karthik-anba** [comment]
I had by mistake added comments for IR-2006 but I was assigned to review IR-2001. Knowing this, I correctly reviewed IR-2001 and removed the comment I added for IR-2006. 

I believe it is now the correct pull request and I am not overwriting other reviews.

**Comment by karthik-anba** [comment]
Closed this pull request and generated a new pull request after discussions with AI (Dimitar).

**Pull request closed without merging**
