### PR TITLE
chg:usr: Pull request Handled by Tony and Student.  duplicated comments. Instr.  can not verify correctness.

### PR DESCRIPTION
**Pull request by eunosm3**

### CODE REVIEW

**Comment by tonythomascn** [comment]
Double bracket is used within author field only if the author name is not a person's name, eg: author={J.K. Rowing}, author={{Amazon Web Services}}.
Please change those.

**Comment by laszewsk** [comment]
Tony, please check this. Msg changed every single entry is pretty alarming ;-)

**Comment by eunosm3** [comment]
I'll change them. Thanks for the pointer.
Also, I should have been more precise.  I changed every single citation for *my assigned technologies*.

Best,
~ML

Get Outlook for iOS




On Thu, Feb 16, 2017 at 6:36 PM -0500, "tonythomascn" <notifications@github.com> wrote:












Double bracket is used within author field only if the author name is not a person's name, eg: author={J.K. Rowing}, author={{Amazon Web Services}}.

Please change those.

**Comment by eunosm3** [comment]
I changed the non-person "authors" field to include double curly braces, most of which were Wikipedia references.  I wasn't sure about this one, though.  -->>{{Windows Club{,} The}}  Is it correct?



If so, I'll make a new pull request.




~ML



Download Outlook for Android









On Thu, Feb 16, 2017 at 6:36 PM -0500, "tonythomascn" <notifications@github.com> wrote:












Double bracket is used within author field only if the author name is not a person's name, eg: author={J.K. Rowing}, author={{Amazon Web Services}}.

Please change those.

**Comment by tonythomascn** [comment]
I don’t understand. Is there an organization or agent called Windows Club, The?

Also, please don’t create a new pull request. All modifications/commits will show within your current pull request.

**Comment by eunosm3** [comment]
It is called The Windows Club.  As for writing it as "Windows Club, The", putting the "The" at the end is a long-standing habit so that sorting alphabetically returns more-meaningful results versus clustering together all titles that start with the word "The".  I'll modify it any way you want, though.


I'll forego the new pull request. Before I edited the refs.bib file just now,  I issued "git fetch upstream" and "git rebase upstream/master".  So, do I simply re-issue the "git push origin master" command in order to send the updates to the outstanding pull request?  I'd like to avoid making your life more difficult.




~ML



Download Outlook for Android






From: tonythomascn

Sent: Thursday, February 16, 10:27 PM

Subject: Re: [cloudmesh/classes] chg:usr: updated every single citation (#332)

To: cloudmesh/classes

Cc: eunosm3, Author



I don’t understand. Is there an organization or agent called Windows Club, The?


Also, please don’t create a new pull request. All modifications/commits will show within your current pull request.

**Comment by tonythomascn** [comment]
I would recommend you to write it as {{The Windows Club}}.

That’s correct. You are on the right track.

I appreciate your cooperation.

Tony

**Comment by eunosm3** [comment]
Erlang Central is the name of the organization/online presence that wrote the piece I cited.  I *thought* I already had it in double curly  braces.  It should be as follows, right: {{Erlang Central}}?


Thanks.




~ML



Download Outlook for Android









On Thu, Feb 16, 2017 at 10:23 PM -0500, "tonythomascn" <notifications@github.com> wrote:












@tonythomascn requested changes on this pull request.



Please correct author for www-wikipedia-erlang-cbs,www-apachephoenix-org,www-blobqueuetable. Thanks.

**Comment by tonythomascn** [comment]
I think so. Unless the author’s first name is Erlang and last name Central.

**Comment by eunosm3** [comment]
one more question before I push the changes upstream - I usually  include the message, using the -m flag, with my commit command.  Does it need to match the prior one?  Do I need it at all?  Etc.




~ML



Download Outlook for Android









On Thu, Feb 16, 2017 at 10:45 PM -0500, "tonythomascn" <notifications@github.com> wrote:










I would recommend you to write it as {{The Windows Club}}.



That’s correct. You are on the right track.



I appreciate your cooperation.



Tony

**Comment by tonythomascn** [comment]
For each commit, your commit message should relate to your current modification. I recommend to read help with git commit --help, or man git commit.

**Comment by tonythomascn** [comment]
One last suggestion to you. In the future, avoid to submit everything within one commit or one pull request. The probability of containing errors within such a huge commit is so high that most likely your pull request will not be accepted.

**Comment by eunosm3** [comment]
Understood.  Thanks for the tip.






~ML



Download Outlook for Android









On Thu, Feb 16, 2017 at 11:10 PM -0500, "tonythomascn" <notifications@github.com> wrote:












One last suggestion to you. In the future, avoid to submit everything within one commit or one pull request. The probability of containing errors within such a huge commit is so high that most likely your pull request will not be accepted.

**Comment by eunosm3** [comment]
Changes have been made and pushed.  I appreciate your help.  




~ML



Download Outlook for Android









On Thu, Feb 16, 2017 at 11:10 PM -0500, "tonythomascn" <notifications@github.com> wrote:












One last suggestion to you. In the future, avoid to submit everything within one commit or one pull request. The probability of containing errors within such a huge commit is so high that most likely your pull request will not be accepted.

**Comment by eunosm3** [comment]
If I revised my work correctly, I am *not* making a new pull request, but I *do* want this one to be merged.  FWIW: The conversation is a back-and-forth between me and tonythomascn about which changes to make.  It culminates in him explaining that the revisions I made should be reflected automatically in the current pull  request; that is, I do not need to create a new pull request.

Is that responsive?

**Comment by laszewsk** [comment]
I am dismissing my review, as i can not follow what happened. Students needs to work with Tony to get this approved and integrated. comments are duplicated and do not follow proper formating for me to review this pull request. If student wants to however get me involed a new "clean" pull request is needed. Furthermore without Tonts additional work I am no longer ab le to check correctness of this pull request as he is a reviewer and I can therefore at thsi time not initiate a branch update

**Comment by laszewsk** [comment]
I made some updates in the previous comment, pointing out that I can no longer test if this pull request does not introduce a conflict. As Tony mentines this is ok, its in Tonys responsibility to work with the student. Student. please send tone a private message on piazza so he can integrate this with you. I will rename pull request so I do not constantly revisit it.

**Comment by eunosm3** [comment]
I receive "Updates were rejected because the tip of your current branch is behind its remote counterpart."
It suggests using 'git pull' to resolve the issue.  "git pull ... " what, though?

**Comment by tonythomascn** [comment]
Rebase with upstream and try again

**Comment by eunosm3** [comment]
I already have... after I commit, I use git fetch upstream and then git rebase upstream/master.  Only then do I issue the git push origin master command.

**Comment by tonythomascn** [comment]
Did your push succeed? Can you see them on your remote repo?

**Comment by eunosm3** [comment]
Do we want to continue chasing this?  If I can withdraw the PR, I can copy my reference changes, nuke my local repository, delete the online  repository under my name and start over.  It doesn't take that long.

**Comment by tonythomascn** [comment]
OK. You can do that.

**Comment by eunosm3** [comment]
So, how do I withdraw a request?

**Comment by tonythomascn** [comment]
I can close it.

**Comment by eunosm3** [comment]
Cool.  I'm working on my plan as we banter.

**Pull request closed without merging**
