### PR TITLE
new:usr: ERROR readded fixed references and updated descriptions

### PR DESCRIPTION
**Pull request by michaelsmith1983**
for stackato, parasol vcloud and vsphere, totem, and libvirt

### CODE REVIEW

**Comment by michaelsmith1983** [comment]
how do I resolve a conflict, I am new to github

**Comment by michaelsmith1983** [comment]
I think I fixed the conflict, could you please advise if I was  successful

**Comment by laszewsk** [comment]
You need to visit this pull request on the Web page. YoU can look up if the pull request creates a conflict this way. I do not have to be involved. Having said this, as you can see it does create a conflict.

**Comment by laszewsk** [comment]
Action required: 
A) either get in contact with TA which will probably recommend B or do B yourself
B) (work with TA if unclear)
make a backup of your currently cloned dir
delete your fork on github
create a new for in githup
clone that new for
integrate your changes from the backup carefully
do a commit and push
create a new pull request

**Comment by michaelsmith1983** [comment]
thank you for  guidance, I will focus on this issue when I get home from work today.

**Pull request closed without merging**
