### PR TITLE
new:usr: Added technologies graphdb, LDAP and Cobbler to the Techlist

### PR DESCRIPTION
**Pull request by ronak1182**

### CODE REVIEW

**Comment by ronak1182** [comment]
Hi Dimitar,

If you can approve my earlier pull request.

I will update LDAP and send a new pull request.

Thanks,
Ronak Parekh

**Comment by dimitargnikolov** [comment]
You can just make the changes, commit and push. This will add the new commit to this pull request.

**Comment by ronak1182** [comment]
So do I need to do a rebase before I make my changes?

**Comment by dimitargnikolov** [comment]
No, don't do a rebase, since I just approved another pull request. Just make the changes, commit and push, and if there are any problems I will take care of it.

**Comment by ronak1182** [comment]
I am not able to push. I committed my changes and it is giving me an error
which states "Failed to push some refs to git@github.com:
ronak1182/classes.git"
Updates were rejected because the remote contains work that you do not have
locally.

**Comment by dimitargnikolov** [comment]
I am on Zoom now and can take a look: https://IU.zoom.us/j/880172901

**Pull request merged**
