### PR TITLE
new:dev: added drafts for Ansibl and project, early version needs revise

### PR DESCRIPTION
**Pull request by miaozhan**
Ansible index still contains incorrect items, need to fix

### CODE REVIEW

**Comment by miaozhan** [comment]
Not exactly sure, but this line may cause some character error:
https://github.com/cloudmesh/classes/blob/master/docs/source/refs.bib#L1961

Anyway, this pull request doesn't mean to be pulled. Just a draft so we can critique.

The more advanced Ansible example should be digested and re-written in a different lesson with proper acknowledgements.

**Comment by laszewsk** [comment]
did not cause issue for me, i changed anyways just to make sure.

I will now look into printing non ascii chars in the file to see if a student put some hidden non ascii chars in it

**Comment by miaozhan** [comment]
close it for now, as the repo needs to be re-forked.

@badi Are we going to apply the modified Travis script to ignore the pdf test?

@dimitargnikolov This question just occurred in my mind: What would be the best way to collaborate on editing? Draft versions should not be pulled into the official master, but how can we sync then?

**Comment by badi** [comment]
On Wed, Feb 8, 2017 at 12:19 PM, miaozhan <notifications@github.com> wrote:

> @badi <https://github.com/badi> Are we going to apply the modified Travis
> script to ignore the pdf test?
>
Its merged into master. Any new PRs should have it.

> @dimitargnikolov <https://github.com/dimitargnikolov> This question just
> occurred in my mind: What would be the best way to collaborate on editing?
> Draft versions should not be pulled into the official master, but how can
> we sync then?
>
> Work on one of your forks. You should be add the other as a collaborator
and push/pull changes there.
If you create a PR immediately you can verify that travis passes for each
commit.



-- 

Badi' Abdul-Wahid

**Comment by dimitargnikolov** [comment]
@miaozhan Maybe we can just agree on when each will work on it? If you want to make any changes today, I can work on updating the draft tomorrow morning. We can do this on the master branch, since the draft is already there.

**Pull request closed without merging**
