### PR TITLE
Add bin/split_video_for_youtube.sh

### PR DESCRIPTION
**Pull request by dimitargnikolov**
Adding the script to split videos into chunks that can be uploaded to YouTube.

### CODE REVIEW

**Comment by dimitargnikolov** [comment]
Nevermind, I will redo this since I was working on the master branch of my fork.

**Comment by badi** [comment]
I fixed this already in #11

**Comment by dimitargnikolov** [comment]
Thanks! I'll also make sure I use the comment protocol in the future.

I take it that we should work on the master branch and not on i524?

**Comment by badi** [comment]
Yes. Master branch please.

**Pull request closed without merging**
