### PR TITLE
new:usr: add description about Potree

### PR DESCRIPTION
**Pull request by narayana1043**
new:usr: add description about Potree

### CODE REVIEW

**Comment by tonythomascn** [comment]
Second bib entry should be inProceedings instead of Misc.

**Comment by tonythomascn** [comment]
I think most likely could be the url within 
@Misc{potree-paper-1,
  Title                    = {Taming the beast: Free and open-source massive point cloud web visualization},
  Author                   = {Martinez-Rubi.O, Verhoeven.S and others},
  Year                     = {2015-11-25},
  Owner                    = {S17-IR-2017},
  Timestamp                = {2017.02.13},
  Url                      = {http://repository.tudelft.nl/islandora/object/uuid:0472e0d1-ec75-465a-840e-fd53d427c177?collection=research}
}
It's not acceptable within Travis CI.
Could you fix this entry and try push again with another url?

**Comment by laszewsk** [comment]
I recommend a new fork and integration of your content into that new fork. This is far simplere than trying to fix your current version with a rebase.

**Comment by laszewsk** [comment]
i commented, authors are wrong

**Comment by narayana1043** [comment]
I tried to put the names of all the authors but I got an error saying that the author field is too long

**Comment by laszewsk** [comment]
please email me entry with complet author list, in any cae you need to not use , oin author field

**Comment by tonythomascn** [comment]
Sorry, I accientally close it.

**Comment by tonythomascn** [comment]
@narayana1043 After you fix, can you please create another pull request?

**Pull request closed without merging**
