### PR TITLE
new:usr: Added IBM Watson to techlist

### PR DESCRIPTION
**Pull request by vorasagar7**

### CODE REVIEW

**Comment by vorasagar7** [comment]
Hi Dimitar,

I did rebase to it.
So should I rebase it again and do it ?

Warm Regards,

*Sagar Vora*
MS in CS graduate Fall 2016 at *Indiana University*
<https://www.indiana.edu/>
Email: savora@iu.edu
Mobile No: + <%2B91%209833869966>1 8123698537
Linkedin <https://in.linkedin.com/in/sagar-vora-856b6615>

**Comment by dimitargnikolov** [comment]
Actually, yes, I see you rebased. 

However, if you look at the "Files Changed" tab and the refs.bib entry, you will see that you not only added your new entries, but ended up changing every other entry in the file. It looks like it's the formatting of the white space before the '=' characters. Maybe your editor reformatted everything?

To keep changes small, could you commit a version of refs.bib that only has your new bib entries and doesn't change what is currently there?

You could do the following:
1. Create a backup of refs.bib
2. Revert to the version of refs.bib in the repo: git checkout docs/source/refs.bib
3. Put only your new entries in refs.bib and commit it. 

Let me know of any questions.

**Comment by vorasagar7** [comment]
ok.

So tell me what should I do, like how do I revert to the previous version.

I actually added the entry and then did the reformatting thingy as
mentioned in the video. I did it via emacs as told on the video call which
happened day before yesterday. Can you guide me here please ?

Warm Regards,

*Sagar Vora*
MS in CS graduate Fall 2016 at *Indiana University*
<https://www.indiana.edu/>
Email: savora@iu.edu
Mobile No: + <%2B91%209833869966>1 8123698537
Linkedin <https://in.linkedin.com/in/sagar-vora-856b6615>

**Comment by dimitargnikolov** [comment]
Ok, I looked through all the changes and will approve. 

Thanks for reformatting all the entries. In the future, go ahead and only change entries for techs assigned to you, since we want to avoid confusing the other students by changing their entries frequently.

**Pull request merged**
