### PR TITLE
new:usr: Added UIMA_Jena_AzureDataFactory_Tycoon to techlist

### PR DESCRIPTION
**Pull request by sowravi**
New request to merge 4 technologies
1. UIMA
2. Jena
3. Azure Data Factory
4. Tycoon

### CODE REVIEW

**Comment by laszewsk** [comment]
this would mean it should not be approved

**Comment by dimitargnikolov** [comment]
@laszewsk Ok. This seemed minor, so I just mentioned it, but won't approve in the future.

@sowravi, please fix the entry and review the rest in case anything else is incorrect.

**Comment by laszewsk** [comment]
yes, lets accept this time.

**Comment by sowravi** [comment]
Thanks for accepting. My H-Id is S17-IR-2030 and one of the technologies that I was assigned was google data flow. I see that another person (Hid - S17-IO-3013) was also assigned the same technology. It would be very helpful if you could clarify the final list of technologies that I have to submit.

Thanks,
Sowmya

**Comment by dimitargnikolov** [comment]
Sowmya, 

Google Cloud DataFlow appears twice in the list: as number 24 in the Workflow Orchestration section and as number 124 in the High Level Programming section. The 24 entry has been filled, while the 124 entry is empty.

I would take a look at what your classmate wrote, and if you feel like there is anything you can add or change, please do that under entry 124. Otherwise, you can simply copy the 24 entry in the 124 position as well. 

@laszewsk, does that sound good to you?

**Comment by laszewsk** [comment]
Why not simply say

see entry 24 

No copying needed. However a technology could address towo different aspects, take a look at what category they are in and focus on this category.

HOewver for references if you use the same do not duplicate

**Comment by sowravi** [comment]
I have some content ready for that. However, it is majorly similar to what is already there. I would like it add that anyway.

**Pull request merged**
