### PR TITLE
new usr: Appending Dryad , DB2 and 1d changes

### PR DESCRIPTION
**Pull request by shah0112**
new usr: Appending Dryad , DB2 and 1d changes

### CODE REVIEW

**Comment by shah0112** [comment]
Hi,

In the error log below, we see that error is reported in files new.rst which I have not altered. Is there something that can be done?  make and make view run successfully in my local.

WARNING: duplicate label for keys las14cloudmeshmultiple and www-bpel-wiki
WARNING: duplicate label for keys las14cloudmeshmultiple and www-bpel-wiki
/data/docs/source/class-i524/spring-2017/new.rst:: ERROR: Anonymous hyperlink mismatch: 72 references but 0 targets.
See "backrefs" attribute for IDs.
/data/docs/source/class-i524/spring-2017/old/old.rst:: ERROR: Anonymous hyperlink mismatch: 72 references but 0 targets.
See "backrefs" attribute for IDs.
/data/docs/source/files/python/faq.rst:106: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/docs/source/files/python/faq.rst:109: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/docs/source/files/python/faq.rst:120: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/docs/source/files/python/faq.rst:133: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/docs/source/files/python/faq.rst:146: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/docs/source/files/python/faq.rst:153: WARNING: Block quote ends without a blank line; unexpected unindent.
/data/docs/source/files/python/faq.rst:25: ERROR: Undefined substitution referenced: "image0".
/data/docs/source/format/report/README.rst:17: ERROR: Document may not end with a transition.

**Comment by dimitargnikolov** [comment]
This error does not appear in the current build, so it could be something unrelated to the files you mention. There are a number of errors. One is about a non unicode character by Latex. 

Are you able to build the project on your machine as-is? If not, you might need to make a backup in order to preserve your changes, then refork, and add your changes again.

**Comment by shah0112** [comment]
Hi,

I am able to make the file without any error in my local. Also I tried doing everything from the beginning, reforked it again and pushed it! It's still throwing errors in travis build 

Regards,
Shahidhya Ramachandran

**Comment by dimitargnikolov** [comment]
This seems like a problem we'll have to look at together then. 

Are you able to be on Zoom at 6pm tonight for @jemitchell's office hours? 

Alternatively, I can chat on Zoom tonight after 10:30pm, or tomorrow from 1 to 2pm.

**Comment by laszewsk** [comment]
current build does not show this error.

**Comment by shah0112** [comment]
Hi,

We can look at it by 10:30 

Regards,
Shahidhya Ramachandran

**Comment by dimitargnikolov** [comment]
Ok, we can talk on Zoom. Closing this PR, since you opened #459.

**Pull request closed without merging**
