### PR TITLE
new:dev: Add rkt,Heroku,Pegasus,Drill,Titan:db

### PR DESCRIPTION
**Pull request by yatinsharma7**
Added explanation about rkt, Heroku, Pegasus,Drill,Titan:db

### CODE REVIEW

**Comment by yatinsharma7** [comment]
how do I resolve the branch conflict?

**Comment by laszewsk** [comment]
easiest way:

a) create new fork from what is in the repo, add your changes in that new fork

second easiest:

b) work with TA in online session

third easiest

c) read up on how to resolve a convlict and how it is shown in the code and remove the conflict after rebasing in your current repo. This could cause other issues that may be more time consuming than a and b)

**Comment by yatinsharma7** [comment]
Thanks professor!
Yes option#1 seems to be the easiest but I think I will try to resolve these conflicts with the TA's because I want to get this branching and re-basing concept clear.

**Comment by laszewsk** [comment]
there will be plenty of time in class to do that …. so no hurry on this, get homework done first

**Comment by yatinsharma7** [comment]
Alright Professor.
I am going ahead with option#1 and have already created a new pull request #282 for that.
Do you want me to delete this particular pull request?

**Comment by dimitargnikolov** [comment]
Closing, since #282 was approved.

**Pull request closed without merging**
