### PR TITLE
new:usr: improve: use ASCII: adding Dryad, DB2, making reference changes mentioned in review

### PR DESCRIPTION
**Pull request by shah0112**

### CODE REVIEW

**Comment by shah0112** [comment]
Hi,
Travis build has failed and it is throwing errors in files that I have not modified. Same problem existed the last time I submitted. Dimitar tried running my file locally and it worked. Please let me know what must be done.

**Comment by laszewsk** [comment]
Github gives very clear feedback that are directly related to your checkins. Clearly the errors are not related to other files that you have not modified. The issue is that you use non ASCII characters pasted and copied wither from a Web page or from word. github even tells you what is wrong, including the character that you use.  ⊆ Is not ASCII. Only thinkg you had to do was looking for the word error in the output generated by github. So please describe with other terms the  ⊆ 

I have not checked other things, but this would probably be a good start. E.g. github tells you 

! Package inputenc Error: Unicode char ⊆ (U+2286)
(inputenc)                not set up for use with LaTeX.
See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.5429 directed edges and two sets IG ⊆
                                          VG and OG ⊆ VG that indicate the
! Package inputenc Error: Unicode char ⊆ (U+2286)
(inputenc)                not set up for use with LaTeX.
See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.5429 ... edges and two sets IG ⊆ VG and OG ⊆
                                                   VG that indicate the
LaTeX Warning: Hyper reference `i524/technologies:paper-naiad' on page 66 undef
ined on input line 5436.

**Comment by shah0112** [comment]
Thank you Professor! The checks have passed.

**Comment by laszewsk** [comment]
I am so glad it worked.

**Pull request merged**
