### PR TITLE
chg: usr: change structure of tech page to load techs from separate files

### PR DESCRIPTION
**Pull request by dimitargnikolov**
In this way, the students don't have to all edit technologies.rst which makes merging their pull requests less conflict prone.

### CODE REVIEW

**Comment by laszewsk** [comment]
although nice this is risky as homework video needs to be reshot and students may complain that requiremenst of submitting homework has changed shortly before submit. So we need to make sure that this is an option only and the old way still can be done. 

does the chackin contain documentation that maskes it clear?

**Comment by dimitargnikolov** [comment]
No, I haven't added the docs for this yet.

I see what you're saying about the video and changing the process.

We could introduce this for the next TechList homework perhaps?

**Comment by dimitargnikolov** [comment]
The same applies for the more recent commit, which creates different bib
file for each HID and updates the Makefile.

I will keep these modifications in a separate branch on my fork, and we can
merge them into the repo on Monday for the next homework, if they look good
otherwise and everyone is happy with this process.

**Comment by laszewsk** [comment]
THis can only be done if its all worked out

for example, you may need to leave of the 

.. include in the techlist for all non added technologies and still have students do the includsion of the include to make it similar.

however, maybe its best to keep it unchanged till the end of the month when homework is due. 

the bib file is naturally working …. 

i think we are a bit to late with this change and it shoudl have been suggested before we do the announcement.

**Comment by laszewsk** [comment]
I agree, this will create too many changes 
If I were a students and woudl see 3 days before teh homework is due such a change I would be not happy and complain

**Comment by dimitargnikolov** [comment]
Ok, sounds good. All the files are edited/generated by scripts, so we can
just rerun next month for the new homework if we decide to take that route.

**Pull request closed without merging**
