### PR TITLE
new:dev: configure publish from travis

### PR DESCRIPTION
**Pull request by badmutex**
The approach is:

1. Create a new passwordless ssh key.
1. Encrypt the private key (`deploy_key`) to `deploy_key.enc` using `travis encrypt-file deploy_key --add`
1. Upload the public key (`deploy_key.pub`) to `repo/settings/keys`
1. Git ignore deploy_key
1. Update travis to decrypt the key and use it to publish using `make publish`

This change include adaptation of instructions from:

- https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
- https://oncletom.io/2016/travis-ssh-deploy/

### CODE REVIEW

**Comment by badi** [comment]
@laszewsk I think this should be ready to merge.
I do have a concern though: the build logs on travis seem to indicate that graphviz is not installed correctly.
See here: https://travis-ci.org/cloudmesh/classes/builds/195662602#L1603

We should wait on merging this until we are both in the office to cleanup if/when things break.

**Comment by laszewsk** [comment]
graphviz needs to be installed via aptget or so into the vm. we need that to verify the image. If not an error could occur elsewhere but we never check as it already bombs in graphviz if its not installed.

this would also mean nothing would ever be green

**Review by laszewsk — CHANGES_REQUESTED** [review]
make sure graphviz check passes also

**Comment by laszewsk** [comment]
can you sesolve the conflicts in travis. They are produced by you, so you should probably fix

**Comment by laszewsk** [comment]
anny update on this

**Comment by badi** [comment]
I can finish it up next week. I've been waiting this week to see if any
more bugs are shaken out of the Travis+docker build system.

--

**Comment by laszewsk** [comment]
can you finish this, I still see conflicts

**Comment by laszewsk** [comment]
this pull requests has conflicts thus i can ot approve.

I can only approve pull requests that have no conflicts. you can look ata pull request to identify if they have issues and if they do you need to fix them. We are not doing this.

Furthermore, the indication that you have a deploy_key in the directory where you work showcases that you do not follow best practices by not haveing ANY keys in the directories where you do developments in.

**Comment by laszewsk** [comment]
can you finish this?

**Pull request closed without merging**
