### PR TITLE
deleted ENV and added changes to refs.bib

### PR DESCRIPTION
**Pull request by Anveling**

### CODE REVIEW

**Comment by laszewsk** [comment]
please have meeting with TAs

**Comment by laszewsk** [comment]
This pull request has multiple errors.

a) adding my-refs and my-technologies is not allowed
b) creating duplicated bibtex entries
d) not created the classes web page locally

**Comment by laszewsk** [comment]
There is NO possibility that we can accept the pull request as you have not kept up with the class and did not do a rebase. Please meat with a TA in case you do not know how to use git to fix this. 
My recommendation would be to make a backup, do a complete new fork, add whatever it is that you need to add to the new for, make sure you do not introduce any error and than do the pull request. 

While you will spend DAYS on fixing your current pull request, you will spend only minutes doing what i suggest. Again, please consult with the TAs as it is obvious that we can not accept this pull request.

**Comment by Anveling** [comment]
Thank You, Sir.

**Pull request closed without merging**
